package utils

import dev.newteam.newteam3.plantilla.models.Entrenador
import dev.newteam.newteam3.plantilla.models.Jugador
import dev.newteam.newteam3.plantilla.models.Persona
import dev.newteam.newteam3.utils.html
import org.junit.jupiter.api.Test
import java.awt.Desktop
import java.io.File
import java.time.LocalDate

class HtmlMuppetTest {

    private val html = html()

    @Test
    fun generarYVerHtmlMuppet() {
        val personas = listOf(
            Jugador(
                id = 1,
                nombre = "Hikaru",
                apellido = "Matsuyama",
                fechaNacimiento = LocalDate.of(1971, 4, 3),
                fechaIncorporacion = LocalDate.of(1983, 5, 1),
                salario = 42000.0,
                pais = "Japón",
                rol = "Jugador",
                posicion = Jugador.Posicion.MEDIOCENTRO,
                dorsal = 8,
                altura = 1.47,
                peso = 39.5,
                goles = 32,
                partidosJugados = 62,
                minutosJugados = 5580,
                equipo = Persona.Equipos.MUPPET,
                imagen = "",
                mediaGoles = 3.0
            ),
            Jugador(
                id = 2,
                nombre = "Ken",
                apellido = "Wakashimazu",
                fechaNacimiento = LocalDate.of(1970, 12, 1),
                fechaIncorporacion = LocalDate.of(1983, 5, 1),
                salario = 45500.0,
                pais = "Japón",
                rol = "Jugador",
                posicion = Jugador.Posicion.PORTERO,
                dorsal = 1,
                altura = 1.52,
                peso = 43.0,
                goles = 0,
                partidosJugados = 60,
                minutosJugados = 5400,
                equipo = Persona.Equipos.MUPPET,
                imagen = "",
                mediaGoles = 4.0
            ),
            Jugador(
                id = 3,
                nombre = "Shun",
                apellido = "Nitta",
                fechaNacimiento = LocalDate.of(1971, 6, 6),
                fechaIncorporacion = LocalDate.of(1983, 5, 1),
                salario = 35000.0,
                pais = "Japón",
                rol = "Jugador",
                posicion = Jugador.Posicion.DELANTERO,
                dorsal = 9,
                altura = 1.47,
                peso = 39.0,
                goles = 27,
                partidosJugados = 49,
                minutosJugados = 4410,
                equipo = Persona.Equipos.MUPPET,
                imagen = "",
                mediaGoles = 4.0
            ),
            Jugador(
                id = 4,
                nombre = "Makoto",
                apellido = "Soda",
                fechaNacimiento = LocalDate.of(1971, 12, 5),
                fechaIncorporacion = LocalDate.of(1983, 5, 1),
                salario = 34000.0,
                pais = "Japón",
                rol = "Jugador",
                posicion = Jugador.Posicion.DEFENSA,
                dorsal = 3,
                altura = 1.48,
                peso = 40.0,
                goles = 2,
                partidosJugados = 46,
                minutosJugados = 4140,
                equipo = Persona.Equipos.MUPPET,
                imagen = "",
                mediaGoles = 3.0
            ),
            Jugador(
                id = 5,
                nombre = "Mamoru",
                apellido = "Izawa",
                fechaNacimiento = LocalDate.of(1971, 11, 15),
                fechaIncorporacion = LocalDate.of(1983, 5, 1),
                salario = 34000.0,
                pais = "Japón",
                rol = "Jugador",
                posicion = Jugador.Posicion.MEDIOCENTRO,
                dorsal = 14,
                altura = 1.44,
                peso = 37.5,
                goles = 10,
                partidosJugados = 45,
                minutosJugados = 4050,
                equipo = Persona.Equipos.MUPPET,
                imagen = "",
                mediaGoles = 1.0
            ),
            Jugador(
                id = 6,
                nombre = "Kazuo",
                apellido = "Tachibana",
                fechaNacimiento = LocalDate.of(1971, 7, 1),
                fechaIncorporacion = LocalDate.of(1983, 5, 1),
                salario = 36000.0,
                pais = "Japón",
                rol = "Jugador",
                posicion = Jugador.Posicion.DELANTERO,
                dorsal = 11,
                altura = 1.42,
                peso = 36.5,
                goles = 41,
                partidosJugados = 51,
                minutosJugados = 4590,
                equipo = Persona.Equipos.MUPPET,
                imagen = "",
                mediaGoles = 5.0
            ),
            Jugador(
                id = 7,
                nombre = "Masao",
                apellido = "Tachibana",
                fechaNacimiento = LocalDate.of(1971, 7, 1),
                fechaIncorporacion = LocalDate.of(1983, 5, 1),
                salario = 36000.0,
                pais = "Japón",
                rol = "Jugador",
                posicion = Jugador.Posicion.DELANTERO,
                dorsal = 12,
                altura = 1.42,
                peso = 36.5,
                goles = 40,
                partidosJugados = 51,
                minutosJugados = 4590,
                equipo = Persona.Equipos.MUPPET,
                imagen = "",
                mediaGoles = 7.0
            ),
            Jugador(
                id = 8,
                nombre = "Ryo",
                apellido = "Ishizaki",
                fechaNacimiento = LocalDate.of(1971, 2, 10),
                fechaIncorporacion = LocalDate.of(1983, 5, 1),
                salario = 35000.0,
                pais = "Japón",
                rol = "Jugador",
                posicion = Jugador.Posicion.DEFENSA,
                dorsal = 5,
                altura = 1.48,
                peso = 40.0,
                goles = 3,
                partidosJugados = 64,
                minutosJugados = 5760,
                equipo = Persona.Equipos.MUPPET,
                imagen = "",
                mediaGoles = 10.0
            ),
            Jugador(
                id = 9,
                nombre = "Yuji",
                apellido = "Kido",
                fechaNacimiento = LocalDate.of(1971, 3, 3),
                fechaIncorporacion = LocalDate.of(1983, 5, 1),
                salario = 32000.0,
                pais = "Japón",
                rol = "Jugador",
                posicion = Jugador.Posicion.DEFENSA,
                dorsal = 15,
                altura = 1.44,
                peso = 38.5,
                goles = 1,
                partidosJugados = 42,
                minutosJugados = 3780,
                equipo = Persona.Equipos.MUPPET,
                imagen = "",
                mediaGoles = 2.0
            ),
            Jugador(
                id = 10,
                nombre = "Mitsuru",
                apellido = "Sano",
                fechaNacimiento = LocalDate.of(1971, 8, 14),
                fechaIncorporacion = LocalDate.of(1983, 5, 1),
                salario = 33000.0,
                pais = "Japón",
                rol = "Jugador",
                posicion = Jugador.Posicion.DEFENSA,
                dorsal = 16,
                altura = 1.45,
                peso = 39.0,
                goles = 1,
                partidosJugados = 44,
                minutosJugados = 3960,
                equipo = Persona.Equipos.MUPPET,
                imagen = "",
                mediaGoles = 8.0
            ),
            Jugador(
                id = 11,
                nombre = "Hajime",
                apellido = "Taki",
                fechaNacimiento = LocalDate.of(1971, 3, 12),
                fechaIncorporacion = LocalDate.of(1983, 5, 1),
                salario = 33000.0,
                pais = "Japón",
                rol = "Jugador",
                posicion = Jugador.Posicion.DEFENSA,
                dorsal = 17,
                altura = 1.43,
                peso = 36.0,
                goles = 7,
                partidosJugados = 43,
                minutosJugados = 3870,
                equipo = Persona.Equipos.MUPPET,
                imagen = "",
                mediaGoles = 8.0
            ),
            Jugador(
                id = 12,
                nombre = "Takeshi",
                apellido = "Sawada",
                fechaNacimiento = LocalDate.of(1971, 9, 20),
                fechaIncorporacion = LocalDate.of(1983, 5, 1),
                salario = 33000.0,
                pais = "Japón",
                rol = "Jugador",
                posicion = Jugador.Posicion.DELANTERO,
                dorsal = 7,
                altura = 1.43,
                peso = 37.0,
                goles = 23,
                partidosJugados = 50,
                minutosJugados = 4500,
                equipo = Persona.Equipos.MUPPET,
                imagen = "",
                mediaGoles = 8.0
            ),
            Jugador(
                id = 13,
                nombre = "Kojiro",
                apellido = "Hyuga",
                fechaNacimiento = LocalDate.of(1970, 8, 17),
                fechaIncorporacion = LocalDate.of(1983, 5, 1),
                salario = 47000.0,
                pais = "Japón",
                rol = "Jugador",
                posicion = Jugador.Posicion.DELANTERO,
                dorsal = 10,
                altura = 1.49,
                peso = 42.0,
                goles = 145,
                partidosJugados = 63,
                minutosJugados = 5670,
                equipo = Persona.Equipos.MUPPET,
                imagen = "",
                mediaGoles = 8.0
            ),
            Jugador(
                id = 14,
                nombre = "Hiroshi",
                apellido = "Jito",
                fechaNacimiento = LocalDate.of(1970, 1, 22),
                fechaIncorporacion = LocalDate.of(1983, 5, 1),
                salario = 42000.0,
                pais = "Japón",
                rol = "Jugador",
                posicion = Jugador.Posicion.DEFENSA,
                dorsal = 4,
                altura = 1.55,
                peso = 48.0,
                goles = 5,
                partidosJugados = 65,
                minutosJugados = 5850,
                equipo = Persona.Equipos.MUPPET,
                imagen = "",
                mediaGoles = 8.0
            ),
            Jugador(
                id = 15,
                nombre = "Shingo",
                apellido = "Aoi",
                fechaNacimiento = LocalDate.of(1971, 10, 22),
                fechaIncorporacion = LocalDate.of(1983, 5, 1),
                salario = 37000.0,
                pais = "Japón",
                rol = "Jugador",
                posicion = Jugador.Posicion.MEDIOCENTRO,
                dorsal = 6,
                altura = 1.45,
                peso = 38.0,
                goles = 19,
                partidosJugados = 48,
                minutosJugados = 4320,
                equipo = Persona.Equipos.MUPPET,
                imagen = "",
                mediaGoles = 8.0
            ),
            Jugador(
                id = 16,
                nombre = "Genzo",
                apellido = "Wakabayashi",
                fechaNacimiento = LocalDate.of(1970, 6, 15),
                fechaIncorporacion = LocalDate.of(1983, 5, 1),
                salario = 46000.0,
                pais = "Japón",
                rol = "Jugador",
                posicion = Jugador.Posicion.PORTERO,
                dorsal = 20,
                altura = 1.50,
                peso = 41.0,
                goles = 0,
                partidosJugados = 66,
                minutosJugados = 5940,
                equipo = Persona.Equipos.MUPPET,
                imagen = "",
                mediaGoles = 8.0
            ),
            Jugador(
                id = 17,
                nombre = "Taro",
                apellido = "Misaki",
                fechaNacimiento = LocalDate.of(1970, 5, 5),
                fechaIncorporacion = LocalDate.of(1983, 5, 1),
                salario = 44000.0,
                pais = "Japón",
                rol = "Jugador",
                posicion = Jugador.Posicion.MEDIOCENTRO,
                dorsal = 18,
                altura = 1.46,
                peso = 38.0,
                goles = 85,
                partidosJugados = 60,
                minutosJugados = 5400,
                equipo = Persona.Equipos.NEW_TEAM,
                imagen = "",
                mediaGoles = 8.0
            ),
            Jugador(
                id = 18,
                nombre = "Kenta",
                apellido = "Shimizu",
                fechaNacimiento = LocalDate.of(1971, 1, 19),
                fechaIncorporacion = LocalDate.of(1983, 5, 1),
                salario = 31000.0,
                pais = "Japón",
                rol = "Jugador",
                posicion = Jugador.Posicion.MEDIOCENTRO,
                dorsal = 19,
                altura = 1.44,
                peso = 37.5,
                goles = 6,
                partidosJugados = 39,
                minutosJugados = 3510,
                equipo = Persona.Equipos.NEW_TEAM,
                imagen = "",
                mediaGoles = 8.0
            ),
            Entrenador(
                id = 1,
                nombre = "Kira",
                apellido = "Yoshikazu",
                fechaNacimiento = LocalDate.of(1940, 4, 18),
                fechaIncorporacion = LocalDate.of(1982, 1, 1),
                salario = 60000.0,
                pais = "Japón",
                rol = "Entrenador",
                especializacion = Entrenador.Especializacion.PRINCIPAL,
                equipo = Persona.Equipos.MUPPET,
                imagen = ""
            ),
            Entrenador(
                id = 2,
                nombre = "Munemasa",
                apellido = "Katagiri",
                fechaNacimiento = LocalDate.of(1938, 11, 12),
                fechaIncorporacion = LocalDate.of(1983, 3, 1),
                salario = 58000.0,
                pais = "Japón",
                rol = "Entrenador",
                especializacion = Entrenador.Especializacion.PORTEROS,
                equipo = Persona.Equipos.MUPPET,
                imagen = ""
            )

        )

        val path = html.generateReportMuppet("data/reporte-muppet.html", personas)
        Desktop.getDesktop().browse(File(path).toURI())


    }

}