package utils

import dev.newteam.newteam3.plantilla.models.Entrenador
import dev.newteam.newteam3.utils.html
import dev.newteam.newteam3.plantilla.models.Jugador
import dev.newteam.newteam3.plantilla.models.Persona
import org.junit.jupiter.api.Test
import java.awt.Desktop
import java.io.File
import java.time.LocalDate

class htmlNewTeamTest {

    private val html = html()
    @Test
    fun generarYVerHtml() {
        val personas = listOf(
            Jugador(
                id = 1,
                nombre = "Tsubasa",
                apellido = "Ozora",
                fechaNacimiento = LocalDate.of(1970, 7, 28),
                fechaIncorporacion = LocalDate.of(1983, 4, 1),
                salario = 45000.0,
                pais = "Japón",
                rol = "Jugador",
                posicion = Jugador.Posicion.DELANTERO,
                dorsal = 10,
                altura = 1.45,
                peso = 39.0,
                goles = 158,
                partidosJugados = 68,
                minutosJugados = 6120,
                equipo = Persona.Equipos.NEW_TEAM,
                imagen = "",
                mediaGoles = 17.0
            ),
            Jugador(
                id = 2,
                nombre = "Genzo",
                apellido = "Wakabayashi",
                fechaNacimiento = LocalDate.of(1970, 6, 15),
                fechaIncorporacion = LocalDate.of(1983, 4, 1),
                salario = 46000.0,
                pais = "Japón",
                rol = "Jugador",
                posicion = Jugador.Posicion.PORTERO,
                dorsal = 1,
                altura = 1.50,
                peso = 41.0,
                goles = 0,
                partidosJugados = 66,
                minutosJugados = 5940,
                equipo = Persona.Equipos.NEW_TEAM,
                imagen = "",
                mediaGoles = 19.0
            ),
            Jugador(
                id = 3,
                nombre = "Taro",
                apellido = "Misaki",
                fechaNacimiento = LocalDate.of(1970, 5, 5),
                fechaIncorporacion = LocalDate.of(1983, 4, 1),
                salario = 44000.0,
                pais = "Japón",
                rol = "Jugador",
                posicion = Jugador.Posicion.MEDIOCENTRO,
                dorsal = 11,
                altura = 1.46,
                peso = 38.0,
                goles = 85,
                partidosJugados = 60,
                minutosJugados = 5400,
                equipo = Persona.Equipos.NEW_TEAM,
                imagen = "",
                mediaGoles = 37.0
            ),
            Jugador(
                id = 4,
                nombre = "Ryo",
                apellido = "Ishizaki",
                fechaNacimiento = LocalDate.of(1971, 2, 10),
                fechaIncorporacion = LocalDate.of(1983, 4, 1),
                salario = 35000.0,
                pais = "Japón",
                rol = "Jugador",
                posicion = Jugador.Posicion.DEFENSA,
                dorsal = 3,
                altura = 1.48,
                peso = 40.0,
                goles = 3,
                partidosJugados = 64,
                minutosJugados = 5760,
                equipo = Persona.Equipos.NEW_TEAM,
                imagen = "",
                mediaGoles = 57.0
            ),
            Jugador(
                id = 5,
                nombre = "Kojirō",
                apellido = "Hyuga",
                fechaNacimiento = LocalDate.of(1970, 8, 17),
                fechaIncorporacion = LocalDate.of(1983, 4, 1),
                salario = 47000.0,
                pais = "Japón",
                rol = "Jugador",
                posicion = Jugador.Posicion.DELANTERO,
                dorsal = 9,
                altura = 1.49,
                peso = 42.0,
                goles = 145,
                partidosJugados = 63,
                minutosJugados = 5670,
                equipo = Persona.Equipos.NEW_TEAM,
                imagen = "",
                mediaGoles = 8.0
            ),
            Jugador(
                id = 6,
                nombre = "Hikaru",
                apellido = "Matsuyama",
                fechaNacimiento = LocalDate.of(1971, 4, 3),
                fechaIncorporacion = LocalDate.of(1983, 4, 1),
                salario = 42000.0,
                pais = "Japón",
                rol = "Jugador",
                posicion = Jugador.Posicion.MEDIOCENTRO,
                dorsal = 8,
                altura = 1.47,
                peso = 39.5,
                goles = 32,
                partidosJugados = 62,
                minutosJugados = 5580,
                equipo = Persona.Equipos.NEW_TEAM,
                imagen = "",
                mediaGoles = 172.0
            ),
            Jugador(
            id = 7,
            nombre = "Jun",
            apellido = "Misugi",
            fechaNacimiento = LocalDate.of(1970, 6, 21),
            fechaIncorporacion = LocalDate.of(1983, 4, 1),
            salario = 43000.0,
            pais = "Japón",
            rol = "Jugador",
            posicion = Jugador.Posicion.MEDIOCENTRO,
            dorsal = 6,
            altura = 1.50,
            peso = 40.0,
            goles = 25,
            partidosJugados = 50,
            minutosJugados = 4500,
            equipo = Persona.Equipos.NEW_TEAM,
            imagen = "",
            mediaGoles = 45.0
        ),
        Jugador(
            id = 8,
            nombre = "Kazuo",
            apellido = "Tachibana",
            fechaNacimiento = LocalDate.of(1971, 1, 1),
            fechaIncorporacion = LocalDate.of(1983, 4, 1),
            salario = 37000.0,
            pais = "Japón",
            rol = "Jugador",
            posicion = Jugador.Posicion.DELANTERO,
            dorsal = 7,
            altura = 1.42,
            peso = 37.0,
            goles = 18,
            partidosJugados = 52,
            minutosJugados = 4680,
            equipo = Persona.Equipos.NEW_TEAM,
            imagen = "",
            mediaGoles = 5.0
        ),
        Jugador(
            id = 9,
            nombre = "Masao",
            apellido = "Tachibana",
            fechaNacimiento = LocalDate.of(1971, 1, 1),
            fechaIncorporacion = LocalDate.of(1983, 4, 1),
            salario = 37000.0,
            pais = "Japón",
            rol = "Jugador",
            posicion = Jugador.Posicion.DELANTERO,
            dorsal = 17,
            altura = 1.42,
            peso = 37.0,
            goles = 17,
            partidosJugados = 52,
            minutosJugados = 4680,
            equipo = Persona.Equipos.NEW_TEAM,
            imagen = "",
            mediaGoles = 8.0
        ),
        Jugador(
            id = 10,
            nombre = "Shingo",
            apellido = "Aoi",
            fechaNacimiento = LocalDate.of(1971, 3, 20),
            fechaIncorporacion = LocalDate.of(1983, 4, 1),
            salario = 39000.0,
            pais = "Japón",
            rol = "Jugador",
            posicion = Jugador.Posicion.MEDIOCENTRO,
            dorsal = 12,
            altura = 1.43,
            peso = 38.0,
            goles = 20,
            partidosJugados = 54,
            minutosJugados = 4860,
            equipo = Persona.Equipos.NEW_TEAM,
            imagen = "",
            mediaGoles = 7.0
        ),
        Jugador(
            id = 11,
            nombre = "Mamoru",
            apellido = "Izawa",
            fechaNacimiento = LocalDate.of(1971, 5, 12),
            fechaIncorporacion = LocalDate.of(1983, 4, 1),
            salario = 36000.0,
            pais = "Japón",
            rol = "Jugador",
            posicion = Jugador.Posicion.MEDIOCENTRO,
            dorsal = 4,
            altura = 1.44,
            peso = 39.0,
            goles = 9,
            partidosJugados = 50,
            minutosJugados = 4500,
            equipo = Persona.Equipos.NEW_TEAM,
            imagen = "",
            mediaGoles = 1.0
        ),
        Jugador(
            id = 12,
            nombre = "Teppei",
            apellido = "Kisugi",
            fechaNacimiento = LocalDate.of(1971, 7, 3),
            fechaIncorporacion = LocalDate.of(1983, 4, 1),
            salario = 35500.0,
            pais = "Japón",
            rol = "Jugador",
            posicion = Jugador.Posicion.DELANTERO,
            dorsal = 14,
            altura = 1.43,
            peso = 37.5,
            goles = 11,
            partidosJugados = 47,
            minutosJugados = 4230,
            equipo = Persona.Equipos.NEW_TEAM,
            imagen = "",
            mediaGoles = 0.0
        ),
        Jugador(
            id = 13,
            nombre = "Hajime",
            apellido = "Taki",
            fechaNacimiento = LocalDate.of(1971, 9, 30),
            fechaIncorporacion = LocalDate.of(1983, 4, 1),
            salario = 35000.0,
            pais = "Japón",
            rol = "Jugador",
            posicion = Jugador.Posicion.MEDIOCENTRO,
            dorsal = 13,
            altura = 1.44,
            peso = 38.5,
            goles = 7,
            partidosJugados = 44,
            minutosJugados = 3960,
            equipo = Persona.Equipos.NEW_TEAM,
            imagen = "",
            mediaGoles = 2.0
        ),
        Jugador(
            id = 14,
            nombre = "Shun",
            apellido = "Nitta",
            fechaNacimiento = LocalDate.of(1971, 12, 10),
            fechaIncorporacion = LocalDate.of(1983, 4, 1),
            salario = 36500.0,
            pais = "Japón",
            rol = "Jugador",
            posicion = Jugador.Posicion.DELANTERO,
            dorsal = 15,
            altura = 1.46,
            peso = 39.0,
            goles = 14,
            partidosJugados = 49,
            minutosJugados = 4410,
            equipo = Persona.Equipos.NEW_TEAM,
            imagen = "",
            mediaGoles = 1.0
        ),
        Jugador(
            id = 15,
            nombre = "Ken",
            apellido = "Wakashimazu",
            fechaNacimiento = LocalDate.of(1970, 10, 5),
            fechaIncorporacion = LocalDate.of(1983, 4, 1),
            salario = 45500.0,
            pais = "Japón",
            rol = "Jugador",
            posicion = Jugador.Posicion.PORTERO,
            dorsal = 18,
            altura = 1.51,
            peso = 42.0,
            goles = 0,
            partidosJugados = 58,
            minutosJugados = 5220,
            equipo = Persona.Equipos.NEW_TEAM,
            imagen = "",
            mediaGoles = 7.0
        ),
        Jugador(
            id = 16,
            nombre = "Takeshi",
            apellido = "Sawada",
            fechaNacimiento = LocalDate.of(1971, 8, 8),
            fechaIncorporacion = LocalDate.of(1983, 4, 1),
            salario = 34500.0,
            pais = "Japón",
            rol = "Jugador",
            posicion = Jugador.Posicion.DEFENSA,
            dorsal = 16,
            altura = 1.43,
            peso = 37.0,
            goles = 6,
            partidosJugados = 46,
            minutosJugados = 4140,
            equipo = Persona.Equipos.NEW_TEAM,
            imagen = "",
            mediaGoles = 4.0
        ),
        Jugador(
            id = 17,
            nombre = "Hiroshi",
            apellido = "Jito",
            fechaNacimiento = LocalDate.of(1970, 11, 11),
            fechaIncorporacion = LocalDate.of(1983, 4, 1),
            salario = 40000.0,
            pais = "Japón",
            rol = "Jugador",
            posicion = Jugador.Posicion.DEFENSA,
            dorsal = 2,
            altura = 1.55,
            peso = 45.0,
            goles = 4,
            partidosJugados = 60,
            minutosJugados = 5400,
            equipo = Persona.Equipos.NEW_TEAM,
            imagen = "",
            mediaGoles = 6.0
        ),
        Jugador(
            id = 18,
            nombre = "Makoto",
            apellido = "Soda",
            fechaNacimiento = LocalDate.of(1970, 12, 25),
            fechaIncorporacion = LocalDate.of(1983, 4, 1),
            salario = 39000.0,
            pais = "Japón",
            rol = "Jugador",
            posicion = Jugador.Posicion.DEFENSA,
            dorsal = 19,
            altura = 1.50,
            peso = 41.0,
            goles = 5,
            partidosJugados = 55,
            minutosJugados = 4950,
            equipo = Persona.Equipos.NEW_TEAM,
            imagen = "",
            mediaGoles = 6.0
        ),
            Entrenador(
                id = 1,
                nombre = "Kira",
                apellido = "Yoshikazu",
                fechaNacimiento = LocalDate.of(1940, 4, 18),
                fechaIncorporacion = LocalDate.of(1982, 1, 1),
                salario = 60000.0,
                pais = "Japón",
                rol = "Entrenador",
                especializacion = Entrenador.Especializacion.PORTEROS,
                equipo = Persona.Equipos.MUPPET,
                imagen = ""
            ),
            Entrenador(
                id = 2,
                nombre = "Munemasa",
                apellido = "Katagiri",
                fechaNacimiento = LocalDate.of(1938, 11, 12),
                fechaIncorporacion = LocalDate.of(1983, 3, 1),
                salario = 58000.0,
                pais = "Japón",
                rol = "Entrenador",
                especializacion = Entrenador.Especializacion.PORTEROS,
                equipo = Persona.Equipos.MUPPET,
                imagen = ""
            )
        )

        val path = html.generateReport("data/reporte-newteam.html", personas)
        Desktop.getDesktop().browse(File(path).toURI())
    }
}
